baseURL = "https://zhenghaozhu.github.io"
publishDir = "zhenghaozhu.github.io/"
languageCode = "en-us"
title = "Zhenghao (Kevin) Zhu"
theme = "hello-friend-ng"
copyright = "Zhenghao (Kevin) Zhu" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Book List"
url = "/book-list"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = false # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Hi! My name is Zhenghao (Kevin) Zhu."
  # mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    url = "https://github.com/ZhenghaoZhu"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/zhuzhenghao/"
  [[params.social]]
    name = "email"
    url = "kevinzhuzhenghao@gmail.com"  # no need for "mailto:" in the head
  [[params.social]]
    name = "resume"
    url = "https://drive.google.com/file/d/1B-zOl7RWpCB4oYNKd2pKki-f1M3XrNjl/view?usp=sharing"

[params.logo]
    logoText     = "$ cd /home/kevin"
    logoHomeLink = "/"